### ISSUE TITLE
gulp dist won't run

### ISSUE THREAD

**Issue by jw56578** [tinkertrain/jspm-react#8]
C:\projects\jspm-react>gulp dist
[22:23:07] Using gulpfile C:\projects\jspm-react\gulpfile.js
[22:23:07] Starting 'dist'...
[22:23:07] Starting 'delete-dist'...
[22:23:07] Finished 'delete-dist' after 1.46 ms
[22:23:07] Starting 'js'...
[22:23:07] Starting 'sass'...
[22:23:08] Finished 'dist' after 261 ms
[22:23:08] null
[22:23:08] Finished 'sass' after 301 ms
[22:23:08] Finished 'js' after 333 ms
[22:23:08] Starting 'build'...
[22:23:08] Finished 'build' after 5.7 µs
[22:23:08] Starting 'css'...
[22:23:08] Starting 'html'...
[22:23:08] Finished 'html' after 1.45 ms
[22:23:08] Starting 'js'...
[22:23:08] Finished 'js' after 5.2 ms
[22:23:08] Starting 'bundle'...
[22:23:08] Finished 'css' after 119 ms
     Building the single-file sfx bundle for build/js/main.js!jsx...

err  TypeError: Cannot read property 'suppressDeprecationMessages' of undefined
         at Logger.deprecate (evalmachine.<anonymous>:8889:24)
         at File.normalizeOptions (evalmachine.<anonymous>:8271:18)
         at new File (evalmachine.<anonymous>:8237:22)
         at TransformerPipeline.transform (evalmachine.<anonymous>:12107:16)
         at C:\projects\jspm-react\node_modules\jspm\node_modules\systemjs-build
er\compilers\es6.js:125:31
         at tryCatchReject (C:\projects\jspm-react\node_modules\jspm\node_module
s\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)

```
     at runContinuation1 (C:\projects\jspm-react\node_modules\jspm\node_modu
```

les\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4
)
         at Fulfilled.when (C:\projects\jspm-react\node_modules\jspm\node_module
s\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
         at Pending.run (C:\projects\jspm-react\node_modules\jspm\node_modules\s
ystemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
         at Scheduler._drain (C:\projects\jspm-react\node_modules\jspm\node_modu
les\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)

```
     at Scheduler.drain (C:\projects\jspm-react\node_modules\jspm\node_modul
```

es\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)
[22:23:10] 'bundle' errored after 2.22 s
[22:23:10] Error in plugin 'gulp-shell'
Message:
    Command failed:
Details:
    killed: false
    code: 1
    signal: null
    stdout:      Building the single-file sfx bundle for build/js/main.js!jsx...

err  TypeError: Cannot read property 'suppressDeprecationMessages' of undefined
         at Logger.deprecate (evalmachine.<anonymous>:8889:24)
         at File.normalizeOptions (evalmachine.<anonymous>:8271:18)
         at new File (evalmachine.<anonymous>:8237:22)
         at TransformerPipeline.transform (evalmachine.<anonymous>:12107:16)
         at C:\projects\jspm-react\node_modules\jspm\node_modules\systemjs-build
er\compilers\es6.js:125:31
         at tryCatchReject (C:\projects\jspm-react\node_modules\jspm\node_module
s\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)

```
     at runContinuation1 (C:\projects\jspm-react\node_modules\jspm\node_modu
```

les\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4
)
         at Fulfilled.when (C:\projects\jspm-react\node_modules\jspm\node_module
s\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
         at Pending.run (C:\projects\jspm-react\node_modules\jspm\node_modules\s
ystemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
         at Scheduler._drain (C:\projects\jspm-react\node_modules\jspm\node_modu
les\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)

```
     at Scheduler.drain (C:\projects\jspm-react\node_modules\jspm\node_modul
```

es\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)

```
stderr:
```

Error running task sequence: { task: 'bundle',
  message: 'bundle stream',
  duration: 2.223091719,
  hrDuration: [ 2, 223091719 ],
  err:
   { [Error: Command failed: ]
     killed: false,
     code: 1,
     signal: null,
     stdout: '     Building the single-file sfx bundle for build/js/main.js!jsx.
..\n\nerr  TypeError: Cannot read property \'suppressDeprecationMessages\' of un
defined\n         at Logger.deprecate (evalmachine.<anonymous>:8889:24)\n
  at File.normalizeOptions (evalmachine.<anonymous>:8271:18)\n         at new Fi
le (evalmachine.<anonymous>:8237:22)\n         at TransformerPipeline.transform
(evalmachine.<anonymous>:12107:16)\n         at C:\projects\jspm-react\node_m
odules\jspm\node_modules\systemjs-builder\compilers\es6.js:125:31\n
 at tryCatchReject (C:\projects\jspm-react\node_modules\jspm\node_modules\
systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:3
0)\n         at runContinuation1 (C:\projects\jspm-react\node_modules\jspm\
node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader
.src.js:1142:4)\n         at Fulfilled.when (C:\projects\jspm-react\node_modu
les\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-mo
dule-loader.src.js:930:4)\n         at Pending.run (C:\projects\jspm-react\no
de_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\
\es6-module-loader.src.js:821:13)\n         at Scheduler._drain (C:\projects\j
spm-react\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-
loader\dist\es6-module-loader.src.js:97:19)\n         at Scheduler.drain (C:\
projects\jspm-react\node_modules\jspm\node_modules\systemjs\node_modules\
es6-module-loader\dist\es6-module-loader.src.js:62:9)\n',
     stderr: '',
     name: 'Error',
     message: 'Command failed: ',
     stack: 'Error: Command failed: \n    at ChildProcess.exithandler (child_pro
cess.js:648:15)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (
child_process.js:756:16)\n    at Socket.<anonymous> (child_process.js:969:11)\n
   at Socket.emit (events.js:117:20)\n    at Pipe.close (net.js:465:12)',
     showStack: false,
     showProperties: true,
     plugin: 'gulp-shell' } }

C:\projects\jspm-react>

**Comment by bmcorser** [comment]
:+1: I see this too

**Comment by bmcorser** [comment]
Looks like this is `jspm`/`babel` interop issue, see https://github.com/jspm/jspm-cli/issues/809

I fixed with `jspm install npm:babel-core@5.4.7`

**Comment by bmcorser** [comment]
I notice `jspm install npm:babel-core --latest` also seems to work, but provides some deprecation messages.

**Comment by jw56578** [comment]
Yes that was it. Thanks!
